# Generated by Django 2.1.5 on 2019-02-03 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_course_student_studentcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name_course',
            new_name='name',
        ),
    ]
