# Generated by Django 2.1.5 on 2019-02-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190203_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='name_text',
        ),
    ]
