# Generated by Django 2.1.5 on 2019-02-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_studentcourse_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
